version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: khanh022002
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql  # Tên dịch vụ MySQL trong docker-compose
      MYSQL_ROOT_PASSWORD: yourpassword
    ports:
      - "8081:80"  # Truy cập phpMyAdmin qua http://localhost:8081
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/snapheal?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=khanh022002
    # Đặt biến môi trường dựa trên môi trường Docker