version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: khanh022002
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis  # Ensure Redis starts before spring-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/snapheal?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: khanh022002
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
