spring:
  application:
    name: snapheal
  datasource:
    url: jdbc:mysql://localhost:3306/snapheal?useSSL=false&serverTimezone=UTC
    username: root
    password: khanh022002
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 86400000
    refresh-expiration-time: 2592000000

mail:
  host: smtp.gmail.com
  port: 587
  username: vuvankhanh022002@gmail.com
  password: "ddkb trvv tifc mfuh"
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
      debug: true # Optional for troubleshooting

api:
  prefix: /api/v1
